apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  selector:
    matchLabels:
      app: nginx-prod
      environment: prod
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-prod
        environment: prod
    spec:
      containers:
      - name: nginx-prod
        image: nginx:1.20.0
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
